<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign up</title>
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link rel="stylesheet" href="css/singin.css" />

    <style>
  body{
    background-image: url('image/logo/bg3.png');
    background-size: cover;
  }
  .mycontainer{
  background-color:white;
   width:438px;
   height:80%;
   margin-top:0px;
   margin:auto ;
   border-radius: 30px;
   box-shadow: -1px 2px 5px 15px #f5f5f5d8;
  
  }

</style>
</head>

<body class="text-center">
    <br><br><br>
<div class="mycontainer">
<form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
    <br>
      <img class="mb-4" src="image/logo/1.jpg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
<div class="container">

    <label for="inputName" class="sr-only" >Name</label>
    <input type="text" name="name" class="form-control" value="<?= $_POST['name'] ?? '' ?>" maxlength="50" required="required" placeholder="name must contain only letters, numbers and space">
    <span class="text-danger"><?php if (isset($name_error)) echo $name_error; ?></span>
    
    
    <label for="inputEmail" class="sr-only">Email</label>
    <input type="email" name="email" class="form-control" value="<?= $_POST['email'] ?? '' ?>" placeholder="fooooolen@example.com"  required autofocus>
    <span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
   
    
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="pwd" class="form-control" placeholder="can't be less than 6 characters" required="required">
    <span class="text-danger"><?php if (isset($pwd_error)) echo $password_error; ?></span>
     
   
    <label for="inputConfirmPassword" class="sr-only">Confirm Password</label>
    <input type="password" name="cpwd" class="form-control" placeholder="confirm password" required="required">
    <span class="text-danger"><?php if (isset($cpassword_error)) echo $cpassword_error; ?></span>
    
    <label for="inputPhone" class="sr-only">Phone</label>
    <input type="text" name="phnno" class="form-control" value="<?= $_POST['phnno'] ?? '' ?>" placeholder="can't be less than 8 characters" required="required">
    <span class="text-danger"><?php if (isset($phone_error)) echo $phone_error; ?></span>
   
    <label for="inputAddress" class="sr-only">Address</label>
    <input type="text" name="address" class="form-control" value="<?= $_POST['address'] ?? '' ?>" maxlength="50"  placeholder="Address must contain only letters, numbers and space" required="required">
    <span class="text-danger"><?php if (isset($address_error)) echo $address_error; ?></span>

    <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit" name="signup">Sign up</button>
    <div class="text-center">
    Already have a account?<a href="signin.php" class="btn btn-default">Sign in</a>
    </div>
    </form>
    </div>
    </div>    
</body>
</html>