<!DOCTYPE html>
<html lang="en">
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sign in</title>
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link rel="stylesheet" href="css/singin.css" />
<style>
  body{
    background-image: url('image/logo/bg3.png');
    background-size: cover;
  }
  .mycontainer{
  background-color:white;
   width:400px;
   height:80%;
   margin-top:60px;
   margin:auto ;
   border-radius: 30px;
   box-shadow: -1px 2px 5px 15px #f5f5f5d8;
  
  }
</style>
</head>
<body class="text-center">
    <br><br><br>
<div class="mycontainer">
<?php if (isset($auth_error)): ?>
<div class="alert alert-danger alert-dismissible fade show">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?= $auth_error ?>
</div>
<?php endif ?>
<form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post"><br>
<img class="mb-4" src="image/logo/1.jpg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <div class="container">
       <label for="inputEmail" class="sr-only">Email</label>
       <input type="email" name="email" class="form-control" value="<?= $_POST['email'] ?? '' ?>" placeholder="Your email" required autofocus >
       <span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
                   
        <label  for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="pwd" class="form-control" value="" placeholder="Your password" required>
        <span class="text-danger"><?php if (isset($password_error)) echo $password_error; ?></span>

        <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit" name="login">Sign in</button><br>
    You don't have account?<a href="signup.php" class="mt-3">Click Here</a>
</form>
</div>
</body>
</html>